### ISSUE TITLE
possible additional topics

### ISSUE THREAD

**Issue by yuriykuzin** [javascriptru/angularpro#1]
- rxjs and memory leak protection strategies (takeUntil, async pipe)
- using different interceptors in modules

**Comment by stevermeister** [comment]
different interceptors in modules?

**Comment by yuriykuzin** [comment]
What if we want to fetch data from different apis, with different headers/credentials.

**Comment by stevermeister** [comment]
I don't really see a topic here, just use of interceptors, no?

**Comment by stevermeister** [comment]
разбил на issue на 2 отдельных
