### ISSUE TITLE
todd

### ISSUE THREAD

**Issue by ghost** [javascriptru/angularpro#11]
https://ultimatecourses.com/angular/pro

**Comment by stevermeister** [comment]
какие-то темы остались не покрытыми?

**Comment by ghost** [comment]
Разве что финальный проект

**Comment by stevermeister** [comment]
как сделаем страничку для МК на английском - покажу Тодду, чтобы оценил :)

**Comment by ghost** [comment]
)

**Comment by stevermeister** [comment]
обновим ссылочку - https://ultimatecourses.com/learn/angular-pro
