### ISSUE TITLE
ngRx

### ISSUE THREAD

**Issue by stevermeister** [javascriptru/angularpro#15]
подумываем о создании отдельного МК о реактивностях Angular, куда войдет эта тема

**Comment by ghost** [comment]
Не нужен нгрх, имхо офк. На этом курсе если можно симпл пример как сделать это на сервисах. Один стейт для всего АПП, scan, map, reduce etc

**Comment by stevermeister** [comment]
да, конечно, когда я рассматривал тему ngRx на продвинутом курсе, мы начинали с основ redux, только так можно объяснить зачем там вообще такие архитектурные усложнения в виде ngRx
