### ISSUE TITLE
PWA. Предложение пользователю установить приложение

### ISSUE THREAD

**Issue by muturgan** [javascriptru/angularpro#17]
Это конечно не чисто ангуляровский вопрос, но раз в программе предполагается разобрать такую интересную для меня тему, как pwa: 
Я конечно могу принудительно установить своё pwa на устройство. Однако существующие на рынке сайты сами предлагают пользотелю установить приложение.  А о возможности установить моё приложение пользователь не узнает, если не захочет попробовать (скорее всего не захочет).

Как сделать пользователю такое предложение, я к сожалению пока не разобрался - статей не нашёл (возможно не тот поиск задавал), анализ кода сервис воркеров тоже не помог.

Было бы здорово подсветить этот момент на занятии.

**Comment by stevermeister** [comment]
вот тут расписаны критерии для PWA для chrome
https://developers.google.com/web/fundamentals/app-install-banners/#criteria
chrome должен сам подхватить и предложить.

я видел примеры приложений, которые предлагают поставить мобильную версию, но не PWA. если есть живые примеры где-то под рукой - скиньте пожалуйста

и да, вы правы, это не совсем вопрос о Angular, поэтому issue я закрою

**Comment by muturgan** [comment]
Весьма полезная информация, спасибо!

**Comment by trunkovich** [comment]
@stevermeister там есть возможность перехватывать хромовский попап. И активировать по нажатию на кнопку. Но все равно нужно соблюсти все критерии хрома.

**Comment by trunkovich** [comment]
@stevermeister 
Что-то типа такого
```
  init() {
    if (window.matchMedia('(display-mode: standalone)').matches) {
      this.isPwa$.next(true);
    } else {
      if (this.device.isMobile() && this.device.os === OS.ANDROID) {
        this.window.addEventListener('beforeinstallprompt', (event: BeforeInstallEvent) => this.zone.run(() => {
          this.showAddButton$.next(true);
          this.beforeinstallprompt = event;
          if (this.showLater) {
            this.showAndroidDialog();
          }
        }));
      }
    }
  }
```
