### ISSUE TITLE
Понимание для чего нужен RxJs

### ISSUE THREAD

**Issue by constantant** [javascriptru/angularpro#4]
Как показывает практика, не все понимают зачем нужны потоки.
Наверное, нужно продемонстрировать на непростом примере в чём профит. Например, Todo list с фильтром и опциями для фильтра. 
Сначала реализовать как в учебнике, а потом переписать на потоки.

**Comment by stevermeister** [comment]
добавлено к https://github.com/javascript-ru/angularpro/pull/10
