### ISSUE TITLE
Организация и архитектура приложения, best practices.

### ISSUE THREAD

**Issue by DavidovPavel** [javascriptru/angularpro#7]
Использование компонентов (директив) в разных модулях. Взаимодействие между ними.
На сколько целесообразно разбивать приложение на модули. Импорт - экспорт компонентов из одного модуля в другой. Если приложение очень большое и как в нем не потеряться.

**Comment by stevermeister** [comment]
добавлено в https://github.com/javascript-ru/angularpro/pull/10
